/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chair_low_poly.glb 
Author: SusanKing (https://sketchfab.com/krolzuzannapl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chair-low-poly-65514d0221f5455991f14017cda76ec3
Title: Chair low poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/chair_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chair_body_0.geometry} material={materials.body} position={[0.136, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[78.926, 86.397, 86.397]} />
    </group>
  )
}

useGLTF.preload('/chair_low_poly.glb')
