/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 goose_low_poly.glb 
Author: Atlas (https://sketchfab.com/Atlasmodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goose-low-poly-3318893e41fc4d2f9f497776da95c13a
Title: Goose Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Goose(props) {
  const gooseRef = useRef();
  const { nodes, materials } = useGLTF('/goose_low_poly.glb')
  
  useFrame((state) => {
    const elapsed = state.clock.getElapsedTime() + 5

    const rockingAngle = Math.sin(elapsed * 2) * -0.09

    if (gooseRef.current) {
      gooseRef.current.rotation.y = rockingAngle
    }
  })
  
  return (
    <group {...props} ref={gooseRef} dispose={null}>
      <group position={[-51.056, 0.231, 99.282]} rotation={[-1.538, 0.033, 2.356]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 174.902, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={37.283}>
            <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Plane_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Plane_Material003_0.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/goose_low_poly.glb')
