/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 simple_low_poly_boat.glb 
Author: Jewel John (https://sketchfab.com/jeweljohn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-low-poly-boat-b8684a35976c448d8eca6b11240dd85f
Title: Simple Low poly Boat
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export function Boat(props) {
  const boatRef = useRef();
  const { nodes, materials } = useGLTF('/simple_low_poly_boat.glb')
  
  useFrame((state) => {
    const elapsed = state.clock.getElapsedTime()

    const rockingAngle = Math.sin(elapsed) * 0.08

    if (boatRef.current) {
      boatRef.current.rotation.x = rockingAngle
    }
  })
  
  return (
    <group {...props} dispose={null} ref={boatRef}>
      <group scale={0.01}>
        <mesh geometry={nodes.Hall_Hall_0.geometry} material={materials.Hall} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cabin_Cabin_0.geometry} material={materials.Cabin} position={[0, 225.786, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pole_Pole_0.geometry} material={materials.Pole} position={[0, 735.17, 401.093]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.1, 10.1, 650.922]} />
        <mesh geometry={nodes.Circle_Circle_0.geometry} material={materials.Circle} position={[0, 427.445, 1069.457]} scale={48.397} />
      </group>
    </group>
  )
}

useGLTF.preload('/simple_low_poly_boat.glb')
