/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 suitcase_low_poly.glb 
Author: aetherowl (https://sketchfab.com/aetherowl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/suitcase-low-poly-2267f5a831de4ff0b2a7f653f792269f
Title: Suitcase Low Poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Suitcase(props) {
  const { nodes, materials } = useGLTF('/suitcase_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0, -100]} rotation={[Math.PI, 0, 0]} scale={100}>
          <mesh geometry={nodes.Top_Base_0.geometry} material={materials.Base} />
          <mesh geometry={nodes.Top_Accent_0.geometry} material={materials.Accent} />
          <mesh geometry={nodes.Top_Latch_0.geometry} material={materials.Latch} />
        </group>
        <group position={[0, -84.656, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={93.929}>
          <group position={[0, 0, 0.901]} scale={1.065}>
            <mesh geometry={nodes.Bottom_Base_0.geometry} material={materials.Base} />
            <mesh geometry={nodes.Bottom_Accent_0.geometry} material={materials.Accent} />
            <mesh geometry={nodes.Bottom_Latch_0.geometry} material={materials.Latch} />
          </group>
          <mesh geometry={nodes.Plane_Accent_0.geometry} material={materials.Accent} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/suitcase_low_poly.glb')
