/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_island.glb 
Author: Omar_Mohamed (https://sketchfab.com/Omar_Mohamed)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-island-89c550c91356421dba73f288bd46161b
Title: The Island
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/the_island.glb')
  return (
    <group {...props} dispose={null} scale={0.02}>
      <group position={[-30.362, 125.584, -23.436]} rotation={[-1.514, -0.044, -2.071]} scale={[6.278, 6.278, 4.934]}>
        <mesh geometry={nodes.Icosphere034_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere034_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[11.055, 170.563, 27.687]} rotation={[-1.612, -0.003, -0.145]} scale={[8.546, 8.546, 6.716]}>
        <mesh geometry={nodes.Icosphere036_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere036_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-63.296, 85.711, 28.984]} rotation={[-1.654, 0.001, 3.028]} scale={[4.3, 4.3, 3.379]}>
        <mesh geometry={nodes.Icosphere037_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere037_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-140.369, -4.68, 131.018]} rotation={[-1.469, 0.095, -1.432]} scale={35.241}>
        <mesh geometry={nodes.Cube006_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube006_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-89.592, -3.678, 118.138]} rotation={[-1.702, 0.048, 0.615]} scale={19.714}>
        <mesh geometry={nodes.Cube007_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube007_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-215.186, 380.022, -222.076]} rotation={[-Math.PI / 2, 0, 2.559]} scale={23.905}>
        <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[656.862, 569.327, 497.982]} rotation={[-1.541, -0.361, 0.969]} scale={[5.907, 5.907, 4.643]}>
        <mesh geometry={nodes.Icosphere007_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere007_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[630.654, 540.895, 523.987]} rotation={[-1.638, -0.429, 1.155]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere002_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere002_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[501.611, 548.751, 613.948]} rotation={[-1.812, 0.066, -1.642]} scale={[5.907, 5.907, 4.643]}>
        <mesh geometry={nodes.Icosphere003_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere003_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[517.996, 527.497, 577.339]} rotation={[-1.771, 0.171, -1.424]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere004_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere004_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[531.308, 535.738, 366]} rotation={[-1.427, -0.206, 0.808]} scale={[5.907, 5.907, 4.643]}>
        <mesh geometry={nodes.Icosphere005_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere005_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[355.374, 508.862, 413.761]} rotation={[-1.812, 0.066, -1.642]} scale={[5.907, 5.907, 4.643]}>
        <mesh geometry={nodes.Icosphere006_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere006_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[371.76, 487.608, 377.152]} rotation={[-1.771, 0.171, -1.424]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere008_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere008_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-620.637, 465.049, 558.06]} rotation={[-1.89, 0.045, 1.763]} scale={18.913}>
        <mesh geometry={nodes.Cube001_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube001_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-317.553, 509.063, -319.424]} rotation={[-1.571, 0.041, -1.793]} scale={[6.278, 6.278, 4.934]}>
        <mesh geometry={nodes.Icosphere009_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere009_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-375.188, 489.528, -311.528]} rotation={[-1.32, 0.078, 2.71]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere010_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere010_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-171.42, 366.376, -165.881]} rotation={[-Math.PI / 2, 0, -1.62]} scale={17.493}>
        <mesh geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-709.194, 384.174, -341.236]} rotation={[-1.469, 0.095, -1.432]} scale={32.696}>
        <mesh geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube003_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[524.925, 518.416, 547.206]} rotation={[-1.447, 0.093, 2.325]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere011_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere011_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[393.87, 503.878, -539.836]} rotation={[-1.469, 0.06, 1.524]} scale={17.493}>
        <mesh geometry={nodes.Cube004_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube004_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[481.016, 487.489, -534.953]} rotation={[-1.615, -0.047, -3.129]} scale={23.191}>
        <mesh geometry={nodes.Cube005_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube005_Material003_0.geometry} material={materials['Material.003']} />
      </group>
      <group position={[465.496, 503.82, 484.952]} rotation={[-1.699, 0.078, 2.403]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere012_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere012_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[407.447, 488.368, 430.641]} rotation={[-1.447, 0.093, 2.325]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere013_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere013_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[468.475, 476.284, 384.5]} rotation={[-1.447, 0.093, 2.325]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere014_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere014_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[574.117, 556.896, 491.869]} rotation={[-1.608, -0.07, 2.473]} scale={[6.325, 6.325, 4.971]}>
        <mesh geometry={nodes.Icosphere015_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere015_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[686.886, 600.914, 585.675]} rotation={[-1.608, -0.07, 2.473]} scale={[8.295, 8.295, 6.519]}>
        <mesh geometry={nodes.Icosphere016_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere016_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[377.878, 505.634, 492.505]} rotation={[-1.639, 0.058, 2.38]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere017_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere017_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[419.565, 515.194, 543.279]} rotation={[-1.788, 0.072, 2.502]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere018_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere018_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[433.885, 458.389, 324.364]} rotation={[-1.355, -0.007, 2.33]} scale={[4.212, 4.212, 3.31]}>
        <mesh geometry={nodes.Icosphere019_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere019_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[310.17, 466.831, 357.54]} rotation={[-1.694, -0.035, -1.66]} scale={[4.002, 4.002, 3.145]}>
        <mesh geometry={nodes.Icosphere020_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere020_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[491.812, 496.799, 451.89]} rotation={[-1.447, 0.093, 2.325]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere021_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere021_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[611.364, 552.719, 450.112]} rotation={[-1.554, -0.109, 2.275]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere022_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere022_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[488.459, 552.296, 601.546]} rotation={[-1.704, 0.032, 2.333]} scale={[6.325, 6.325, 4.971]}>
        <mesh geometry={nodes.Icosphere023_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere023_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[505.189, 612.159, 694.785]} rotation={[-1.821, 0.18, 2.295]} scale={[7.193, 7.193, 5.653]}>
        <mesh geometry={nodes.Icosphere024_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere024_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[575.537, 562.225, 620.761]} rotation={[-1.936, -0.03, -1.336]} scale={[7.193, 7.193, 5.653]}>
        <mesh geometry={nodes.Icosphere025_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere025_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[600.562, 567.514, 573.862]} rotation={[-1.608, -0.07, 2.473]} scale={[7.193, 7.193, 5.653]}>
        <mesh geometry={nodes.Icosphere026_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere026_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[508.483, 582.104, 667.03]} rotation={[-1.765, -0.119, 2.213]} scale={[7.193, 7.193, 5.653]}>
        <mesh geometry={nodes.Icosphere027_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere027_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <group position={[535.381, 516.96, 418.568]} rotation={[-1.386, -0.087, 2.289]} scale={[5.199, 5.199, 4.086]}>
        <mesh geometry={nodes.Icosphere028_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icosphere028_Material004_0.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Plane001_Material007_0.geometry} material={materials['Material.007']} position={[-61.04, 1.336, 50.921]} rotation={[-Math.PI / 2, 0, 0]} scale={102.097} />
      <mesh geometry={nodes.Icosphere035_Material006_0.geometry} material={materials['Material.006']} position={[-61.846, 5.912, -11.634]} rotation={[-1.551, 0.052, 3.096]} scale={16.097} />
      <mesh geometry={nodes.Icosphere038_Material006_0.geometry} material={materials['Material.006']} position={[-74.02, 4.022, 9.378]} rotation={[-1.558, -0.055, 0.535]} scale={10.641} />
      <mesh geometry={nodes.Icosphere_Material002_0.geometry} material={materials['Material.002']} position={[0, 446.226, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1000} />
      <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} position={[703.789, 305.816, 0]} rotation={[-Math.PI / 2, 0, -0.076]} scale={1629.573} />
      <mesh geometry={nodes.Icosphere001_Material006_0.geometry} material={materials['Material.006']} position={[-364.969, 397.84, -308.771]} rotation={[-1.471, 0.041, -0.037]} scale={16.097} />
      <mesh geometry={nodes.Icosphere029_Material006_0.geometry} material={materials['Material.006']} position={[464.216, 388.632, 328.882]} rotation={[-1.485, -0.375, 0.058]} scale={30.684} />
      <mesh geometry={nodes.Icosphere030_Material006_0.geometry} material={materials['Material.006']} position={[401.538, 383.238, 311.762]} rotation={[-1.555, -0.107, -1.852]} scale={13.847} />
      <mesh geometry={nodes.Icosphere031_Material006_0.geometry} material={materials['Material.006']} position={[317.093, 421.062, 441.679]} rotation={[-1.717, 0.429, -1.875]} scale={44.316} />
      <mesh geometry={nodes.Icosphere032_Material006_0.geometry} material={materials['Material.006']} position={[271.149, 409.167, 409.588]} rotation={[-2.36, -0.44, -2.224]} scale={30.232} />
      <mesh geometry={nodes.Icosphere033_Material006_0.geometry} material={materials['Material.006']} position={[301.783, 398.204, 400.851]} rotation={[-1.606, 0.102, 1.477]} scale={13.847} />
      <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} position={[-104.642, 1.014, 112.702]} rotation={[-1.594, -0.257, 0.758]} scale={14.445} />
      <mesh geometry={nodes.Cube008_Material008_0.geometry} material={materials['Material.008']} position={[-150.394, 0.433, 120.654]} rotation={[-1.803, -0.114, -0.274]} scale={14.193} />
      <mesh geometry={nodes.Cube009_Material008_0.geometry} material={materials['Material.008']} position={[-95.439, 1.372, 108.79]} rotation={[-1.743, 0.193, -1.556]} scale={14.602} />
      <mesh geometry={nodes.Cube011_Material008_0.geometry} material={materials['Material.008']} position={[-153.941, 1.367, 131.669]} rotation={[-1.531, 0.255, -2.45]} scale={14.5} />
      <mesh geometry={nodes.Cube012_Material008_0.geometry} material={materials['Material.008']} position={[-137.512, 0.881, 115.832]} rotation={[-1.723, 0.21, -1.66]} scale={14.5} />
      <mesh geometry={nodes.Cube013_Material008_0.geometry} material={materials['Material.008']} position={[-83.228, 0.994, 0.74]} rotation={[-1.737, 0.199, -1.591]} scale={14.445} />
      <mesh geometry={nodes.Cube014_Material008_0.geometry} material={materials['Material.008']} position={[-77.652, 0.892, -2.378]} rotation={[-1.594, -0.257, 0.758]} scale={14.445} />
      <mesh geometry={nodes.Cube015_Material008_0.geometry} material={materials['Material.008']} position={[-87.294, 0.619, 10.161]} rotation={[-1.34, -0.116, 1.961]} scale={14.445} />
      <mesh geometry={nodes.Cube016_Material008_0.geometry} material={materials['Material.008']} position={[-77.71, 0.632, 21.162]} rotation={[-1.296, -0.215, 1.312]} scale={14.445} />
      <mesh geometry={nodes.Cube017_Material008_0.geometry} material={materials['Material.008']} position={[-59.017, 0.727, -31.332]} rotation={[-1.819, 0.071, -0.995]} scale={14.445} />
      <mesh geometry={nodes.Cube018_Material008_0.geometry} material={materials['Material.008']} position={[-135.514, 0.943, -18.742]} rotation={[-1.803, -0.114, -0.274]} scale={14.193} />
      <mesh geometry={nodes.Cube019_Material008_0.geometry} material={materials['Material.008']} position={[-98.64, 1.367, 65.654]} rotation={[-1.531, 0.255, -2.45]} scale={14.5} />
      <mesh geometry={nodes.Cube020_Material008_0.geometry} material={materials['Material.008']} position={[-106.112, 0.881, 27.528]} rotation={[-1.723, 0.21, -1.66]} scale={14.5} />
      <mesh geometry={nodes.Cube021_Material008_0.geometry} material={materials['Material.008']} position={[-148.421, 0.881, 41.395]} rotation={[-1.723, 0.21, -1.66]} scale={14.5} />
      <mesh geometry={nodes.Cube022_Material008_0.geometry} material={materials['Material.008']} position={[-100.503, 1.367, -38.041]} rotation={[-1.531, 0.255, -2.45]} scale={14.5} />
      <mesh geometry={nodes.Cube023_Material008_0.geometry} material={materials['Material.008']} position={[-62.886, 0.312, 94.863]} rotation={[-1.803, -0.114, -0.274]} scale={14.193} />
    </group>
  )
}

useGLTF.preload('/the_island.glb')
